//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.0;
import "./Battle.sol";
import "@chainlink/contracts/src/v0.8/KeeperCompatible.sol";

contract Bazooka is Battle, KeeperCompatibleInterface {
    /**
    * Public counter variable
    */
    uint public counter;

    /**
    * Use an interval in seconds and a timestamp to slow execution of Upkeep
    */
    uint public immutable interval;
    uint public lastTimeStamp;

    constructor(uint updateInterval){
      interval = updateInterval;
      lastTimeStamp = block.timestamp;

      counter = 0;
    }

    function checkUpkeep(bytes calldata /* checkData */) external view override returns (bool upkeepNeeded, bytes memory /* performData */) {
        upkeepNeeded = (block.timestamp - lastTimeStamp) > interval;
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata /* performData */) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        if ((block.timestamp - lastTimeStamp) > interval ) {
            lastTimeStamp = block.timestamp;
            for(uint256 i=1; i<=battleID; i++){
                uint256 _amount = (uint256(BattlesMapping[monthNo][i].amount)/uint256(5))*uint256(4);
                if(BattlesMapping[monthNo][i].votes1>BattlesMapping[monthNo][i].votes2){
                    BattlesMapping[monthNo][i].nft1.ownerAddress.transfer(_amount);
                }
                else if(BattlesMapping[monthNo][i].votes1<BattlesMapping[monthNo][i].votes2){
                    BattlesMapping[monthNo][i].nft2.ownerAddress.transfer(_amount);
                }
                else if(BattlesMapping[monthNo][i].votes1==BattlesMapping[monthNo][i].votes2){

                }
            }
        }
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }
}